version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: altbank
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - altbank-network

  altbank-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: altbank-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=rootpassword
      - QUARKUS_DATASOURCE_URL=jdbc:mysql://mysql:3306/altbank
      - quarkus.rest-client."br.com.altbank.resources.CardResourceClient".url=http://localhost:8080
    networks:
      - altbank-network


volumes:
  mysql-data:


networks:
  altbank-network:
    driver: bridge